### ISSUE TITLE
drmaa.errors.AlreadyActiveSessionException

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/GenomeKey2#5]
I'm running into this error in: realigner target creator, Inder realigner and haplotypeCaller: 
Flask is still running on the node so heres the job url
http://ec2-52-10-197-65.us-west-2.compute.amazonaws.com:5000/execution/Test_sureselectv5_5_trial_6/
`
Traceback (most recent call last):
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/genomekey/projects/Cosmos/cosmos/web/views.py", line 59, in stage
    drm_statuses.update(jm.get_drm(drm).drm_statuses(list(tasks)))
  File "/home/genomekey/projects/Cosmos/cosmos/job/drm/drm_drmaa.py", line 66, in drm_statuses
    return {task.drm_jobID: self.decodestatus[self.session.jobStatus(str(task.drm_jobID))] for task in tasks}
  File "/home/genomekey/projects/Cosmos/cosmos/job/drm/drm_drmaa.py", line 66, in <dictcomp>
    return {task.drm_jobID: self.decodestatus[self.session.jobStatus(str(task.drm_jobID))] for task in tasks}
  File "/home/genomekey/projects/Cosmos/cosmos/job/drm/drm_drmaa.py", line 21, in session
    self._session.initialize()
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/drmaa/session.py", line 257, in initialize
    py_drmaa_init(contactString)
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/drmaa/wrappers.py", line 73, in py_drmaa_init
    return _lib.drmaa_init(contact, error_buffer, sizeof(error_buffer))
  File "/home/genomekey/projects/GenomeKey/ve/lib/python2.7/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
AlreadyActiveSessionException: code 11: Initialization failed due to existing DRMAA session.
`

**Comment by egafni** [comment]
Ah, the flask web development server wont work when DRMAA is the DRM.

Launch using gunicorn

gunicorn will not have the same problem:  gunicorn genomekey.web.gunicorn:flask -b 0.0.0.0:4849 -w 4

**Comment by Double-O-ren** [comment]
I've installed and launched gunicorn but I can't seem to get a response when I point the browser at :4849.  
--access-logfile isn't logging any requests

**Comment by egafni** [comment]
Aws security group, sorry.. Change the port to whatever it was before since
that is open

**Comment by Double-O-ren** [comment]
getting 404's

**Comment by egafni** [comment]
Not sure, can drop in tomorrow morning at 9am or Friday afternoon to help u
debug

**Comment by Double-O-ren** [comment]
did you try running it with nginx?

**Comment by egafni** [comment]
No but I don't think that's the issue

**Comment by Double-O-ren** [comment]
Tried changing GenomeKey.conf default drm to 'ge' 
Ran into issue #6

**Comment by Double-O-ren** [comment]
I managed to get one job done 
http://ec2-52-10-197-65.us-west-2.compute.amazonaws.com:5000/execution/Test_sureselectv5_5_trial_7/

but I attempted to start another 
http://ec2-52-10-197-65.us-west-2.compute.amazonaws.com:5000/execution/Test_sureselectv5_5_trial_8/

which gave me the same error

**Comment by Double-O-ren** [comment]
I changed GenomeKey.conf default drm to 'ge' 
INFO: 2015-11-12 20:28:03: <Stage[133] Download_Fastqs_From_S3> Manually killed (2 tasks)
WARNING: 2015-11-12 20:28:03: <Execution[12] Test_sureselectv5_5_trial_8_2> Failed, but finished, output_dir: /genomekey/analysis/Germline/Test_sureselectv5_5_trial_8_2
IOError(u'giving up on /genomekey/analysis/Germline/Test_sureselectv5_5_trial_8_2/log/Download_Fastqs_From_S3/942/stderr_attempt1.txt existing',)

**Comment by egafni** [comment]
why did you change it back to 'ge'?  i think we should stick to drmaa if
possible, but it would be good to understand what is causing the file to
not be there. I don't think it is gluster related, because i believe
stdout/stderr gets funneled through the GridEngine (and it seems this
problem doesn't occur when using drmaa).  Might want to do some googling of
how grid engine handles stdout/stderr files.

I can drop by tomorrow if this is still a problem.  Either in the morning
(have a meeting at 10am) or later in the afternoon

**Comment by Double-O-ren** [comment]
with drmaa I get the same errors. Can you come by in the afternoon Ill be here until 7. Thanks!

**Comment by egafni** [comment]
okay i'll drop by before then.  I'll be able to debug over the weekend if
we can't fix it

**Comment by egafni** [comment]
fixed gunicorn
